-- AlterTable
ALTER TABLE `Beverage` ADD COLUMN `description` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `isBest` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isNew` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `name_en` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `notice` VARCHAR(191) NULL,
    ADD COLUMN `price` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `imgUrl` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `Dessert` ADD COLUMN `description` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `isBest` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isNew` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `name_en` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `notice` VARCHAR(191) NULL,
    ADD COLUMN `price` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `name` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `imgUrl` VARCHAR(191) NOT NULL DEFAULT '';
