-- AlterTable
ALTER TABLE `Beverage` ADD COLUMN `category` ENUM('FIZZIO', 'ESPRESSO', 'COLDBREW', 'BLONDE', 'DECAF', 'RESERVE_ESPRESSO', 'RESERVE_DRIP', 'TEAVANA', 'REFRESHERS', 'BLENDED', 'BREWED', 'OTHERS', 'TRENTA', 'TOGOBAG', 'RTD', 'SPECIAL_STORE') NULL DEFAULT 'OTHERS',
    ADD COLUMN `isHot` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `isIce` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `isRecommended` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `productCode` VARCHAR(191) NULL;
